/**
 * D2 1.13 set item data, auto-generated from SetItems.txt.
 * Source: https://github.com/fabd/diablo2/tree/master/code/d2_113_data
 *
 * 127 set items across 32 sets (112 classIds).
 * 104 classIds have only 1 set item (no stat discriminator needed).
 */

export interface SetItemDef {
  name: string;
  setName: string;
  key: string;
  setKey: string;
  code: string;
  classId: number;
  classIdName: string;
  onlySetForClassId: boolean;
  props: { prop: string; par: string; min: number; max: number }[];
}

export const setItems: Record<string, SetItemDef> = {
  "civerbsward": {name:"Civerb's Ward",setName:"Civerb's Vestments",key:"civerbsward",setKey:"civerbsvestments",code:"lrg",classId:330,classIdName:"largeshield",onlySetForClassId:true,props:[{prop:"ac",par:"",min:15,max:15},{prop:"block",par:"",min:15,max:15}]},
  "civerbsicon": {name:"Civerb's Icon",setName:"Civerb's Vestments",key:"civerbsicon",setKey:"civerbsvestments",code:"amu",classId:520,classIdName:"amulet",onlySetForClassId:false,props:[{prop:"regen-mana",par:"",min:40,max:40},{prop:"regen",par:"",min:4,max:4}]},
  "civerbscudgel": {name:"Civerb's Cudgel",setName:"Civerb's Vestments",key:"civerbscudgel",setKey:"civerbsvestments",code:"gsc",classId:16,classIdName:"grandscepter",onlySetForClassId:true,props:[{prop:"att",par:"",min:75,max:75},{prop:"dmg-max",par:"",min:17,max:23}]},
  "hsarusironheel": {name:"Hsarus' Iron Heel",setName:"Hsarus' Defense",key:"hsarusironheel",setKey:"hsarusdefense",code:"mbt",classId:341,classIdName:"chainboots",onlySetForClassId:true,props:[{prop:"res-fire",par:"",min:25,max:25},{prop:"move2",par:"",min:20,max:20}]},
  "hsarusironfist": {name:"Hsarus' Iron Fist",setName:"Hsarus' Defense",key:"hsarusironfist",setKey:"hsarusdefense",code:"buc",classId:328,classIdName:"buckler",onlySetForClassId:true,props:[{prop:"red-dmg",par:"",min:2,max:2},{prop:"str",par:"",min:10,max:10}]},
  "hsarusironstay": {name:"Hsarus' Iron Stay",setName:"Hsarus' Defense",key:"hsarusironstay",setKey:"hsarusdefense",code:"mbl",classId:346,classIdName:"belt",onlySetForClassId:false,props:[{prop:"res-cold",par:"",min:20,max:20},{prop:"hp",par:"",min:20,max:20}]},
  "cleglawstooth": {name:"Cleglaw's Tooth",setName:"Cleglaw's Brace",key:"cleglawstooth",setKey:"cleglawsbrace",code:"lsd",classId:31,classIdName:"longsword",onlySetForClassId:true,props:[{prop:"att%",par:"",min:30,max:30},{prop:"deadly",par:"",min:50,max:50}]},
  "cleglawsclaw": {name:"Cleglaw's Claw",setName:"Cleglaw's Brace",key:"cleglawsclaw",setKey:"cleglawsbrace",code:"sml",classId:329,classIdName:"smallshield",onlySetForClassId:true,props:[{prop:"ac",par:"",min:17,max:17},{prop:"res-pois-len",par:"",min:75,max:75}]},
  "cleglawspincers": {name:"Cleglaw's Pincers",setName:"Cleglaw's Brace",key:"cleglawspincers",setKey:"cleglawsbrace",code:"mgl",classId:336,classIdName:"chaingloves",onlySetForClassId:true,props:[{prop:"knock",par:"",min:1,max:1},{prop:"slow",par:"",min:25,max:25}]},
  "irathascollar": {name:"Iratha's Collar",setName:"Iratha's Finery",key:"irathascollar",setKey:"irathasfinery",code:"amu",classId:520,classIdName:"amulet",onlySetForClassId:false,props:[{prop:"res-pois",par:"",min:30,max:30},{prop:"res-pois-len",par:"",min:75,max:75}]},
  "irathascuff": {name:"Iratha's Cuff",setName:"Iratha's Finery",key:"irathascuff",setKey:"irathasfinery",code:"tgl",classId:337,classIdName:"lightgauntlets",onlySetForClassId:false,props:[{prop:"res-cold",par:"",min:30,max:30},{prop:"half-freeze",par:"",min:1,max:1}]},
  "irathascoil": {name:"Iratha's Coil",setName:"Iratha's Finery",key:"irathascoil",setKey:"irathasfinery",code:"crn",classId:311,classIdName:"crown",onlySetForClassId:false,props:[{prop:"res-fire",par:"",min:30,max:30},{prop:"res-ltng",par:"",min:30,max:30}]},
  "irathascord": {name:"Iratha's Cord",setName:"Iratha's Finery",key:"irathascord",setKey:"irathasfinery",code:"tbl",classId:347,classIdName:"heavybelt",onlySetForClassId:false,props:[{prop:"ac",par:"",min:25,max:25},{prop:"dmg-min",par:"",min:5,max:5}]},
  "isenhartslightbrand": {name:"Isenhart's Lightbrand",setName:"Isenhart's Armory",key:"isenhartslightbrand",setKey:"isenhartsarmory",code:"bsd",classId:30,classIdName:"broadsword",onlySetForClassId:true,props:[{prop:"dmg-min",par:"",min:10,max:10},{prop:"swing2",par:"",min:20,max:20}]},
  "isenhartsparry": {name:"Isenhart's Parry",setName:"Isenhart's Armory",key:"isenhartsparry",setKey:"isenhartsarmory",code:"gts",classId:333,classIdName:"gothicshield",onlySetForClassId:true,props:[{prop:"ac",par:"",min:40,max:40},{prop:"light-thorns",par:"",min:4,max:4}]},
  "isenhartscase": {name:"Isenhart's Case",setName:"Isenhart's Armory",key:"isenhartscase",setKey:"isenhartsarmory",code:"brs",classId:320,classIdName:"breastplate",onlySetForClassId:true,props:[{prop:"ac",par:"",min:40,max:40},{prop:"red-mag",par:"",min:2,max:2}]},
  "isenhartshorns": {name:"Isenhart's Horns",setName:"Isenhart's Armory",key:"isenhartshorns",setKey:"isenhartsarmory",code:"fhl",classId:309,classIdName:"fullhelm",onlySetForClassId:true,props:[{prop:"dex",par:"",min:6,max:6},{prop:"red-dmg",par:"",min:2,max:2}]},
  "vidalasbarb": {name:"Vidala's Barb",setName:"Vidala's Rig",key:"vidalasbarb",setKey:"vidalasrig",code:"lbb",classId:73,classIdName:"longbattlebow",onlySetForClassId:true,props:[{prop:"ltng-min",par:"",min:1,max:1},{prop:"ltng-max",par:"",min:20,max:20}]},
  "vidalasfetlock": {name:"Vidala's Fetlock",setName:"Vidala's Rig",key:"vidalasfetlock",setKey:"vidalasrig",code:"tbt",classId:342,classIdName:"lightplatedboots",onlySetForClassId:true,props:[{prop:"stam",par:"",min:150,max:150},{prop:"move3",par:"",min:30,max:30}]},
  "vidalasambush": {name:"Vidala's Ambush",setName:"Vidala's Rig",key:"vidalasambush",setKey:"vidalasrig",code:"lea",classId:314,classIdName:"leatherarmor",onlySetForClassId:true,props:[{prop:"ac",par:"",min:50,max:50},{prop:"dex",par:"",min:11,max:11}]},
  "vidalassnare": {name:"Vidala's Snare",setName:"Vidala's Rig",key:"vidalassnare",setKey:"vidalasrig",code:"amu",classId:520,classIdName:"amulet",onlySetForClassId:false,props:[{prop:"hp",par:"",min:15,max:15},{prop:"res-cold",par:"",min:20,max:20}]},
  "milabregasorb": {name:"Milabrega's Orb",setName:"Milabrega's Regalia",key:"milabregasorb",setKey:"milabregasregalia",code:"kit",classId:331,classIdName:"kiteshield",onlySetForClassId:true,props:[{prop:"mag%",par:"",min:20,max:20},{prop:"ac",par:"",min:25,max:25}]},
  "milabregasrod": {name:"Milabrega's Rod",setName:"Milabrega's Regalia",key:"milabregasrod",setKey:"milabregasregalia",code:"wsp",classId:17,classIdName:"warscepter",onlySetForClassId:true,props:[{prop:"pal",par:"",min:1,max:1},{prop:"dmg%",par:"",min:50,max:50},{prop:"light",par:"",min:2,max:2}]},
  "milabregasdiadem": {name:"Milabrega's Diadem",setName:"Milabrega's Regalia",key:"milabregasdiadem",setKey:"milabregasregalia",code:"crn",classId:311,classIdName:"crown",onlySetForClassId:false,props:[{prop:"hp",par:"",min:15,max:15},{prop:"mana",par:"",min:15,max:15}]},
  "milabregasrobe": {name:"Milabrega's Robe",setName:"Milabrega's Regalia",key:"milabregasrobe",setKey:"milabregasregalia",code:"aar",classId:326,classIdName:"ancientarmor",onlySetForClassId:true,props:[{prop:"thorns",par:"",min:3,max:3},{prop:"red-dmg",par:"",min:2,max:2}]},
  "cathansrule": {name:"Cathan's Rule",setName:"Cathan's Traps",key:"cathansrule",setKey:"cathanstraps",code:"bst",classId:66,classIdName:"battlestaff",onlySetForClassId:true,props:[{prop:"fireskill",par:"",min:1,max:1},{prop:"fire-max",par:"",min:10,max:10}]},
  "cathansmesh": {name:"Cathan's Mesh",setName:"Cathan's Traps",key:"cathansmesh",setKey:"cathanstraps",code:"chn",classId:319,classIdName:"chainmail",onlySetForClassId:true,props:[{prop:"ac",par:"",min:15,max:15},{prop:"ease",par:"",min:-50,max:-50}]},
  "cathansvisage": {name:"Cathan's Visage",setName:"Cathan's Traps",key:"cathansvisage",setKey:"cathanstraps",code:"msk",classId:312,classIdName:"mask",onlySetForClassId:true,props:[{prop:"mana",par:"",min:20,max:20},{prop:"res-cold",par:"",min:25,max:25}]},
  "cathanssigil": {name:"Cathan's Sigil",setName:"Cathan's Traps",key:"cathanssigil",setKey:"cathanstraps",code:"amu",classId:520,classIdName:"amulet",onlySetForClassId:false,props:[{prop:"balance1",par:"",min:10,max:10},{prop:"light-thorns",par:"",min:5,max:5}]},
  "cathansseal": {name:"Cathan's Seal",setName:"Cathan's Traps",key:"cathansseal",setKey:"cathanstraps",code:"rin",classId:522,classIdName:"ring",onlySetForClassId:false,props:[{prop:"lifesteal",par:"",min:6,max:6},{prop:"red-dmg",par:"",min:2,max:2}]},
  "tancredscrowbill": {name:"Tancred's Crowbill",setName:"Tancred's Battlegear",key:"tancredscrowbill",setKey:"tancredsbattlegear",code:"mpi",classId:3,classIdName:"militarypick",onlySetForClassId:true,props:[{prop:"att",par:"",min:75,max:75},{prop:"dmg%",par:"",min:80,max:80}]},
  "tancredsspine": {name:"Tancred's Spine",setName:"Tancred's Battlegear",key:"tancredsspine",setKey:"tancredsbattlegear",code:"ful",classId:325,classIdName:"fullplatemail",onlySetForClassId:true,props:[{prop:"hp",par:"",min:40,max:40},{prop:"str",par:"",min:15,max:15}]},
  "tancredshobnails": {name:"Tancred's Hobnails",setName:"Tancred's Battlegear",key:"tancredshobnails",setKey:"tancredsbattlegear",code:"lbt",classId:339,classIdName:"boots",onlySetForClassId:true,props:[{prop:"regen-stam",par:"",min:25,max:25},{prop:"dex",par:"",min:10,max:10}]},
  "tancredsweird": {name:"Tancred's Weird",setName:"Tancred's Battlegear",key:"tancredsweird",setKey:"tancredsbattlegear",code:"amu",classId:520,classIdName:"amulet",onlySetForClassId:false,props:[{prop:"red-dmg",par:"",min:2,max:2},{prop:"red-mag",par:"",min:1,max:1}]},
  "tancredsskull": {name:"Tancred's Skull",setName:"Tancred's Battlegear",key:"tancredsskull",setKey:"tancredsbattlegear",code:"bhm",classId:349,classIdName:"bonehelm",onlySetForClassId:true,props:[{prop:"dmg%",par:"",min:10,max:10},{prop:"att",par:"",min:40,max:40}]},
  "sigonsgage": {name:"Sigon's Gage",setName:"Sigon's Complete Steel",key:"sigonsgage",setKey:"sigonscompletesteel",code:"hgl",classId:338,classIdName:"gauntlets",onlySetForClassId:true,props:[{prop:"str",par:"",min:10,max:10},{prop:"att",par:"",min:20,max:20}]},
  "sigonsvisor": {name:"Sigon's Visor",setName:"Sigon's Complete Steel",key:"sigonsvisor",setKey:"sigonscompletesteel",code:"ghm",classId:310,classIdName:"greathelm",onlySetForClassId:true,props:[{prop:"mana",par:"",min:30,max:30},{prop:"ac",par:"",min:25,max:25}]},
  "sigonsshelter": {name:"Sigon's Shelter",setName:"Sigon's Complete Steel",key:"sigonsshelter",setKey:"sigonscompletesteel",code:"gth",classId:324,classIdName:"gothicplate",onlySetForClassId:true,props:[{prop:"ac%",par:"",min:25,max:25},{prop:"res-ltng",par:"",min:30,max:30}]},
  "sigonssabot": {name:"Sigon's Sabot",setName:"Sigon's Complete Steel",key:"sigonssabot",setKey:"sigonscompletesteel",code:"hbt",classId:343,classIdName:"greaves",onlySetForClassId:true,props:[{prop:"move2",par:"",min:20,max:20},{prop:"res-cold",par:"",min:40,max:40}]},
  "sigonswrap": {name:"Sigon's Wrap",setName:"Sigon's Complete Steel",key:"sigonswrap",setKey:"sigonscompletesteel",code:"hbl",classId:348,classIdName:"platedbelt",onlySetForClassId:true,props:[{prop:"res-fire",par:"",min:20,max:20},{prop:"hp",par:"",min:20,max:20}]},
  "sigonsguard": {name:"Sigon's Guard",setName:"Sigon's Complete Steel",key:"sigonsguard",setKey:"sigonscompletesteel",code:"tow",classId:332,classIdName:"towershield",onlySetForClassId:true,props:[{prop:"allskills",par:"",min:1,max:1},{prop:"block",par:"",min:20,max:20}]},
  "infernalcranium": {name:"Infernal Cranium",setName:"Infernal Tools",key:"infernalcranium",setKey:"infernaltools",code:"cap",classId:306,classIdName:"cap",onlySetForClassId:false,props:[{prop:"res-all",par:"",min:10,max:10},{prop:"dmg-to-mana",par:"",min:20,max:20}]},
  "infernaltorch": {name:"Infernal Torch",setName:"Infernal Tools",key:"infernaltorch",setKey:"infernaltools",code:"gwn",classId:13,classIdName:"grimwand",onlySetForClassId:true,props:[{prop:"dmg-min",par:"",min:8,max:8},{prop:"nec",par:"",min:1,max:1}]},
  "infernalsign": {name:"Infernal Sign",setName:"Infernal Tools",key:"infernalsign",setKey:"infernaltools",code:"tbl",classId:347,classIdName:"heavybelt",onlySetForClassId:false,props:[{prop:"ac",par:"",min:25,max:25},{prop:"hp",par:"",min:20,max:20}]},
  "berserkersheadgear": {name:"Berserker's Headgear",setName:"Berserker's Garb",key:"berserkersheadgear",setKey:"berserkersgarb",code:"hlm",classId:308,classIdName:"helm",onlySetForClassId:true,props:[{prop:"ac",par:"",min:15,max:15},{prop:"res-fire",par:"",min:25,max:25}]},
  "berserkershauberk": {name:"Berserker's Hauberk",setName:"Berserker's Garb",key:"berserkershauberk",setKey:"berserkersgarb",code:"spl",classId:321,classIdName:"splintmail",onlySetForClassId:true,props:[{prop:"red-mag",par:"",min:2,max:2},{prop:"bar",par:"",min:1,max:1}]},
  "berserkershatchet": {name:"Berserker's Hatchet",setName:"Berserker's Garb",key:"berserkershatchet",setKey:"berserkersgarb",code:"2ax",classId:2,classIdName:"doubleaxe",onlySetForClassId:true,props:[{prop:"att%",par:"",min:30,max:30},{prop:"manasteal",par:"",min:5,max:5}]},
  "deathshand": {name:"Death's Hand",setName:"Death's Disguise",key:"deathshand",setKey:"deathsdisguise",code:"lgl",classId:334,classIdName:"leathergloves",onlySetForClassId:true,props:[{prop:"res-pois",par:"",min:50,max:50},{prop:"res-pois-len",par:"",min:75,max:75}]},
  "deathsguard": {name:"Death's Guard",setName:"Death's Disguise",key:"deathsguard",setKey:"deathsdisguise",code:"lbl",classId:344,classIdName:"sash",onlySetForClassId:true,props:[{prop:"ac",par:"",min:20,max:20},{prop:"nofreeze",par:"",min:1,max:1}]},
  "deathstouch": {name:"Death's Touch",setName:"Death's Disguise",key:"deathstouch",setKey:"deathsdisguise",code:"wsd",classId:32,classIdName:"warsword",onlySetForClassId:true,props:[{prop:"dmg%",par:"",min:25,max:25},{prop:"lifesteal",par:"",min:4,max:4}]},
  "angelicsickle": {name:"Angelic Sickle",setName:"Angelical Raiment",key:"angelicsickle",setKey:"angelicalraiment",code:"sbr",classId:27,classIdName:"sabre",onlySetForClassId:true,props:[{prop:"att",par:"",min:75,max:75},{prop:"dmg-undead",par:"",min:250,max:250}]},
  "angelicmantle": {name:"Angelic Mantle",setName:"Angelical Raiment",key:"angelicmantle",setKey:"angelicalraiment",code:"rng",classId:317,classIdName:"ringmail",onlySetForClassId:true,props:[{prop:"red-dmg",par:"",min:3,max:3},{prop:"ac%",par:"",min:40,max:40}]},
  "angelichalo": {name:"Angelic Halo",setName:"Angelical Raiment",key:"angelichalo",setKey:"angelicalraiment",code:"rin",classId:522,classIdName:"ring",onlySetForClassId:false,props:[{prop:"regen",par:"",min:6,max:6},{prop:"hp",par:"",min:20,max:20}]},
  "angelicwings": {name:"Angelic Wings",setName:"Angelical Raiment",key:"angelicwings",setKey:"angelicalraiment",code:"amu",classId:520,classIdName:"amulet",onlySetForClassId:false,props:[{prop:"light",par:"",min:3,max:3},{prop:"dmg-to-mana",par:"",min:20,max:20}]},
  "arctichorn": {name:"Arctic Horn",setName:"Arctic Gear",key:"arctichorn",setKey:"arcticgear",code:"swb",classId:74,classIdName:"shortwarbow",onlySetForClassId:true,props:[{prop:"att%",par:"",min:20,max:20},{prop:"dmg%",par:"",min:50,max:50}]},
  "arcticfurs": {name:"Arctic Furs",setName:"Arctic Gear",key:"arcticfurs",setKey:"arcticgear",code:"qui",classId:313,classIdName:"quiltedarmor",onlySetForClassId:true,props:[{prop:"ac%",par:"",min:275,max:325},{prop:"res-all",par:"",min:10,max:10}]},
  "arcticbinding": {name:"Arctic Binding",setName:"Arctic Gear",key:"arcticbinding",setKey:"arcticgear",code:"vbl",classId:345,classIdName:"lightbelt",onlySetForClassId:true,props:[{prop:"res-cold",par:"",min:40,max:40},{prop:"ac",par:"",min:30,max:30}]},
  "arcticmitts": {name:"Arctic Mitts",setName:"Arctic Gear",key:"arcticmitts",setKey:"arcticgear",code:"tgl",classId:337,classIdName:"lightgauntlets",onlySetForClassId:false,props:[{prop:"hp",par:"",min:20,max:20},{prop:"swing1",par:"",min:10,max:10}]},
  "arcannassign": {name:"Arcanna's Sign",setName:"Arcanna's Tricks",key:"arcannassign",setKey:"arcannastricks",code:"amu",classId:520,classIdName:"amulet",onlySetForClassId:false,props:[{prop:"mana",par:"",min:15,max:15},{prop:"regen-mana",par:"",min:20,max:20}]},
  "arcannasdeathwand": {name:"Arcanna's Deathwand",setName:"Arcanna's Tricks",key:"arcannasdeathwand",setKey:"arcannastricks",code:"wst",classId:67,classIdName:"warstaff",onlySetForClassId:true,props:[{prop:"sor",par:"",min:1,max:1},{prop:"deadly",par:"",min:25,max:25}]},
  "arcannashead": {name:"Arcanna's Head",setName:"Arcanna's Tricks",key:"arcannashead",setKey:"arcannastricks",code:"skp",classId:307,classIdName:"skullcap",onlySetForClassId:true,props:[{prop:"regen",par:"",min:4,max:4},{prop:"thorns",par:"",min:2,max:2}]},
  "arcannasflesh": {name:"Arcanna's Flesh",setName:"Arcanna's Tricks",key:"arcannasflesh",setKey:"arcannastricks",code:"ltp",classId:327,classIdName:"lightplate",onlySetForClassId:true,props:[{prop:"light",par:"",min:2,max:2},{prop:"red-dmg",par:"",min:3,max:3}]},
  "natalyastotem": {name:"Natalya's Totem",setName:"Natalya's Odium",key:"natalyastotem",setKey:"natalyasodium",code:"xh9",classId:395,classIdName:"grimhelm",onlySetForClassId:true,props:[{prop:"ac",par:"",min:135,max:175},{prop:"dex",par:"",min:20,max:30},{prop:"str",par:"",min:10,max:20},{prop:"res-all",par:"",min:10,max:20},{prop:"red-mag",par:"",min:3,max:3}]},
  "natalyasmark": {name:"Natalya's Mark",setName:"Natalya's Odium",key:"natalyasmark",setKey:"natalyasodium",code:"7qr",classId:195,classIdName:"scissorssuwayyah",onlySetForClassId:true,props:[{prop:"swing3",par:"",min:40,max:40},{prop:"dmg%",par:"",min:200,max:200},{prop:"ignore-ac",par:"",min:1,max:1},{prop:"dmg-cold",par:"100",min:50,max:50},{prop:"dmg-fire",par:"",min:12,max:17},{prop:"dmg-undead",par:"",min:200,max:200},{prop:"dmg-demon",par:"",min:200,max:200}]},
  "natalyasshadow": {name:"Natalya's Shadow",setName:"Natalya's Odium",key:"natalyasshadow",setKey:"natalyasodium",code:"ucl",classId:434,classIdName:"loricatedmail",onlySetForClassId:true,props:[{prop:"ac",par:"",min:150,max:225},{prop:"hp/lvl",par:"8",min:0,max:0},{prop:"skilltab",par:"19",min:2,max:2},{prop:"res-pois-len",par:"",min:75,max:75},{prop:"res-pois",par:"",min:25,max:25},{prop:"sock",par:"",min:1,max:3}]},
  "natalyassoul": {name:"Natalya's Soul",setName:"Natalya's Odium",key:"natalyassoul",setKey:"natalyasodium",code:"xmb",classId:387,classIdName:"meshboots",onlySetForClassId:true,props:[{prop:"ac",par:"",min:75,max:125},{prop:"move3",par:"",min:40,max:40},{prop:"regen-stam/lvl",par:"2",min:0,max:0},{prop:"dur",par:"",min:50,max:50},{prop:"res-cold",par:"",min:15,max:25},{prop:"res-ltng",par:"",min:15,max:25}]},
  "aldursstonygaze": {name:"Aldur's Stony Gaze",setName:"Aldur's Watchtower",key:"aldursstonygaze",setKey:"aldurswatchtower",code:"dr8",classId:470,classIdName:"hunter'sguise",onlySetForClassId:true,props:[{prop:"ac",par:"",min:90,max:90},{prop:"regen-mana",par:"",min:17,max:17},{prop:"light",par:"",min:5,max:5},{prop:"balance3",par:"",min:25,max:25},{prop:"res-cold",par:"",min:40,max:50},{prop:"sock",par:"",min:2,max:2}]},
  "aldursdeception": {name:"Aldur's Deception",setName:"Aldur's Watchtower",key:"aldursdeception",setKey:"aldurswatchtower",code:"uul",classId:441,classIdName:"shadowplate",onlySetForClassId:true,props:[{prop:"ac",par:"",min:300,max:300},{prop:"skilltab",par:"16",min:1,max:1},{prop:"str",par:"",min:20,max:20},{prop:"dex",par:"",min:15,max:15},{prop:"res-ltng",par:"",min:40,max:50},{prop:"ease",par:"",min:-50,max:-50},{prop:"skilltab",par:"17",min:1,max:1}]},
  "aldursgauntlet": {name:"Aldur's Gauntlet",setName:"Aldur's Watchtower",key:"aldursgauntlet",setKey:"aldurswatchtower",code:"9mt",classId:113,classIdName:"jaggedstar",onlySetForClassId:true,props:[{prop:"dmg-norm",par:"",min:40,max:62},{prop:"dmg-ltng",par:"",min:50,max:75},{prop:"lifesteal",par:"",min:10,max:10},{prop:"swing3",par:"",min:30,max:30},{prop:"dmg-demon",par:"",min:200,max:200},{prop:"manasteal",par:"",min:5,max:5},{prop:"sock",par:"",min:2,max:5}]},
  "aldursadvance": {name:"Aldur's Advance",setName:"Aldur's Watchtower",key:"aldursadvance",setKey:"aldurswatchtower",code:"xtb",classId:388,classIdName:"battleboots",onlySetForClassId:true,props:[{prop:"indestruct",par:"",min:1,max:1},{prop:"regen-stam",par:"",min:32,max:32},{prop:"hp",par:"",min:50,max:50},{prop:"dmg-to-mana",par:"",min:10,max:10},{prop:"move3",par:"",min:40,max:40},{prop:"stam",par:"",min:180,max:180},{prop:"res-fire",par:"",min:40,max:50}]},
  "immortalkingswill": {name:"Immortal King's Will",setName:"Immortal King",key:"immortalkingswill",setKey:"immortalking",code:"ba5",classId:407,classIdName:"avengerguard",onlySetForClassId:true,props:[{prop:"ac",par:"",min:125,max:125},{prop:"gold%",par:"",min:37,max:37},{prop:"skilltab",par:"14",min:2,max:2},{prop:"light",par:"",min:4,max:4},{prop:"mag%",par:"",min:25,max:40},{prop:"sock",par:"",min:2,max:2}]},
  "immortalkingssoulcage": {name:"Immortal King's Soul Cage",setName:"Immortal King",key:"immortalkingssoulcage",setKey:"immortalking",code:"uar",classId:442,classIdName:"sacredarmor",onlySetForClassId:true,props:[{prop:"ac",par:"",min:400,max:400},{prop:"gethit-skill",par:"52",min:5,max:5},{prop:"skilltab",par:"12",min:2,max:2},{prop:"res-pois",par:"",min:50,max:50}]},
  "immortalkingsdetail": {name:"Immortal King's Detail",setName:"Immortal King",key:"immortalkingsdetail",setKey:"immortalking",code:"zhb",classId:394,classIdName:"warbelt",onlySetForClassId:true,props:[{prop:"ac",par:"",min:36,max:36},{prop:"res-fire",par:"",min:28,max:28},{prop:"res-ltng",par:"",min:31,max:31},{prop:"str",par:"",min:25,max:25}]},
  "immortalkingsforge": {name:"Immortal King's Forge",setName:"Immortal King",key:"immortalkingsforge",setKey:"immortalking",code:"xhg",classId:384,classIdName:"wargauntlets",onlySetForClassId:true,props:[{prop:"ac",par:"",min:65,max:65},{prop:"str",par:"",min:20,max:20},{prop:"dex",par:"",min:20,max:20},{prop:"gethit-skill",par:"38",min:12,max:4}]},
  "immortalkingspillar": {name:"Immortal King's Pillar",setName:"Immortal King",key:"immortalkingspillar",setKey:"immortalking",code:"xhb",classId:389,classIdName:"warboots",onlySetForClassId:true,props:[{prop:"ac",par:"",min:75,max:75},{prop:"move3",par:"",min:40,max:40},{prop:"att",par:"",min:110,max:110},{prop:"hp",par:"",min:44,max:44}]},
  "immortalkingsstonecrusher": {name:"Immortal King's Stone Crusher",setName:"Immortal King",key:"immortalkingsstonecrusher",setKey:"immortalking",code:"7m7",classId:219,classIdName:"ogremaul",onlySetForClassId:true,props:[{prop:"indestruct",par:"",min:1,max:1},{prop:"swing3",par:"",min:40,max:40},{prop:"dmg-demon",par:"",min:200,max:200},{prop:"dmg-undead",par:"",min:200,max:200},{prop:"crush",par:"",min:35,max:40},{prop:"dmg%",par:"",min:200,max:200},{prop:"sock",par:"",min:2,max:2}]},
  "talrashasfirespuncloth": {name:"Tal Rasha's Fire-Spun Cloth",setName:"Tal Rasha's Wrappings",key:"talrashasfirespuncloth",setKey:"talrashaswrappings",code:"zmb",classId:392,classIdName:"meshbelt",onlySetForClassId:true,props:[{prop:"ease",par:"",min:-20,max:-20},{prop:"mana",par:"",min:30,max:30},{prop:"dex",par:"",min:20,max:20},{prop:"dmg-to-mana",par:"",min:37,max:37},{prop:"mag%",par:"",min:10,max:15}]},
  "talrashasadjudication": {name:"Tal Rasha's Adjudication",setName:"Tal Rasha's Wrappings",key:"talrashasadjudication",setKey:"talrashaswrappings",code:"amu",classId:520,classIdName:"amulet",onlySetForClassId:false,props:[{prop:"res-ltng",par:"",min:33,max:33},{prop:"sor",par:"",min:2,max:2},{prop:"hp",par:"",min:50,max:50},{prop:"dmg-ltng",par:"",min:3,max:32},{prop:"mana",par:"",min:42,max:42}]},
  "talrashaslidlesseye": {name:"Tal Rasha's Lidless Eye",setName:"Tal Rasha's Wrappings",key:"talrashaslidlesseye",setKey:"talrashaswrappings",code:"oba",classId:290,classIdName:"swirlingcrystal",onlySetForClassId:true,props:[{prop:"hp",par:"",min:57,max:57},{prop:"mana",par:"",min:77,max:77},{prop:"enr",par:"",min:10,max:10},{prop:"cast3",par:"",min:20,max:20},{prop:"skill",par:"Fire Mastery",min:1,max:2},{prop:"skill",par:"Lightning Mastery",min:1,max:2},{prop:"skill",par:"Cold Mastery",min:1,max:2}]},
  "talrashashowlingwind": {name:"Tal Rasha's Howling Wind",setName:"Tal Rasha's Wrappings",key:"talrashashowlingwind",setKey:"talrashaswrappings",code:"uth",classId:440,classIdName:"lacqueredplate",onlySetForClassId:true,props:[{prop:"ease",par:"",min:-60,max:-60},{prop:"red-mag",par:"",min:15,max:15},{prop:"mag%",par:"",min:88,max:88},{prop:"res-cold",par:"",min:40,max:40},{prop:"res-fire",par:"",min:40,max:40},{prop:"res-ltng",par:"",min:40,max:40},{prop:"ac",par:"",min:400,max:400}]},
  "talrashashoradriccrest": {name:"Tal Rasha's Horadric Crest",setName:"Tal Rasha's Wrappings",key:"talrashashoradriccrest",setKey:"talrashaswrappings",code:"xsk",classId:358,classIdName:"deathmask",onlySetForClassId:true,props:[{prop:"mana",par:"",min:30,max:30},{prop:"hp",par:"",min:60,max:60},{prop:"ac",par:"",min:45,max:45},{prop:"res-all",par:"",min:15,max:15},{prop:"lifesteal",par:"",min:10,max:10},{prop:"manasteal",par:"",min:10,max:10}]},
  "griswoldsvalor": {name:"Griswold's Valor",setName:"Griswold's Legacy",key:"griswoldsvalor",setKey:"griswoldslegacy",code:"urn",classId:427,classIdName:"corona",onlySetForClassId:true,props:[{prop:"ac%",par:"",min:50,max:75},{prop:"abs-cold/lvl",par:"",min:2,max:2},{prop:"sock",par:"",min:2,max:2},{prop:"ease",par:"",min:-40,max:-40},{prop:"mag%",par:"",min:20,max:30},{prop:"res-all",par:"",min:5,max:5}]},
  "griswoldsheart": {name:"Griswold's Heart",setName:"Griswold's Legacy",key:"griswoldsheart",setKey:"griswoldslegacy",code:"xar",classId:372,classIdName:"ornateplate",onlySetForClassId:true,props:[{prop:"ac",par:"",min:500,max:500},{prop:"skilltab",par:"11",min:2,max:2},{prop:"sock",par:"",min:3,max:3},{prop:"str",par:"",min:20,max:20},{prop:"ease",par:"",min:-40,max:-40}]},
  "griswoldssredemption": {name:"Griswolds's Redemption",setName:"Griswold's Legacy",key:"griswoldssredemption",setKey:"griswoldslegacy",code:"7ws",classId:213,classIdName:"caduceus",onlySetForClassId:true,props:[{prop:"dmg%",par:"",min:200,max:240},{prop:"swing2",par:"",min:40,max:40},{prop:"dmg-undead",par:"",min:200,max:200},{prop:"ease",par:"",min:-20,max:-20},{prop:"sock",par:"",min:3,max:4}]},
  "griswoldshonor": {name:"Griswold's Honor",setName:"Griswold's Legacy",key:"griswoldshonor",setKey:"griswoldslegacy",code:"paf",classId:502,classIdName:"vortexshield",onlySetForClassId:true,props:[{prop:"ac",par:"",min:108,max:108},{prop:"sock",par:"3",min:0,max:0},{prop:"block2",par:"",min:65,max:65},{prop:"block",par:"",min:20,max:20},{prop:"res-all",par:"",min:45,max:45}]},
  "trangoulsguise": {name:"Trang-Oul's Guise",setName:"Trang-Oul's Avatar",key:"trangoulsguise",setKey:"trangoulsavatar",code:"uh9",classId:465,classIdName:"bonevisage",onlySetForClassId:true,props:[{prop:"ac",par:"",min:80,max:100},{prop:"balance2",par:"",min:25,max:25},{prop:"thorns",par:"",min:20,max:20},{prop:"mana",par:"",min:150,max:150},{prop:"regen",par:"",min:5,max:5}]},
  "trangoulsscales": {name:"Trang-Oul's Scales",setName:"Trang-Oul's Avatar",key:"trangoulsscales",setKey:"trangoulsavatar",code:"xul",classId:371,classIdName:"chaosarmor",onlySetForClassId:true,props:[{prop:"ease",par:"",min:-40,max:-40},{prop:"ac-miss",par:"",min:100,max:100},{prop:"res-pois",par:"",min:40,max:40},{prop:"skilltab",par:"8",min:2,max:2},{prop:"move3",par:"",min:40,max:40},{prop:"ac%",par:"",min:150,max:150}]},
  "trangoulswing": {name:"Trang-Oul's Wing",setName:"Trang-Oul's Avatar",key:"trangoulswing",setKey:"trangoulsavatar",code:"ne9",classId:486,classIdName:"cantortrophy",onlySetForClassId:true,props:[{prop:"ac",par:"",min:125,max:125},{prop:"str",par:"",min:25,max:25},{prop:"dex",par:"",min:15,max:15},{prop:"res-fire",par:"",min:38,max:45},{prop:"block",par:"",min:30,max:30},{prop:"res-pois",par:"",min:40,max:40},{prop:"skilltab",par:"7",min:2,max:2}]},
  "trangoulsclaws": {name:"Trang-Oul's Claws",setName:"Trang-Oul's Avatar",key:"trangoulsclaws",setKey:"trangoulsavatar",code:"xmg",classId:382,classIdName:"heavybracers",onlySetForClassId:true,props:[{prop:"ac",par:"",min:30,max:30},{prop:"cast3",par:"",min:20,max:20},{prop:"res-cold",par:"",min:30,max:30},{prop:"skilltab",par:"6",min:2,max:2}]},
  "trangoulsgirth": {name:"Trang-Oul's Girth",setName:"Trang-Oul's Avatar",key:"trangoulsgirth",setKey:"trangoulsavatar",code:"utc",classId:463,classIdName:"trollbelt",onlySetForClassId:true,props:[{prop:"ac",par:"",min:75,max:100},{prop:"stam",par:"",min:30,max:30},{prop:"regen",par:"",min:5,max:5},{prop:"hp",par:"",min:66,max:66},{prop:"nofreeze",par:"",min:1,max:1},{prop:"ease",par:"",min:-40,max:-40},{prop:"mana",par:"",min:25,max:50}]},
  "mavinastruesight": {name:"M'avina's True Sight",setName:"M'avina's Battle Hymn",key:"mavinastruesight",setKey:"mavinasbattlehymn",code:"ci3",classId:421,classIdName:"diadem",onlySetForClassId:true,props:[{prop:"ac",par:"",min:150,max:150},{prop:"regen",par:"",min:10,max:10},{prop:"swing2",par:"",min:30,max:30},{prop:"mana",par:"",min:25,max:25}]},
  "mavinasembrace": {name:"M'avina's Embrace",setName:"M'avina's Battle Hymn",key:"mavinasembrace",setKey:"mavinasbattlehymn",code:"uld",classId:439,classIdName:"krakenshell",onlySetForClassId:true,props:[{prop:"gethit-skill",par:"55",min:10,max:3},{prop:"ease",par:"",min:-30,max:-30},{prop:"red-mag",par:"",min:5,max:12},{prop:"skilltab",par:"1",min:2,max:2},{prop:"ac/lvl",par:"32",min:0,max:0},{prop:"ac",par:"",min:350,max:350}]},
  "mavinasicyclutch": {name:"M'avina's Icy Clutch",setName:"M'avina's Battle Hymn",key:"mavinasicyclutch",setKey:"mavinasbattlehymn",code:"xtg",classId:383,classIdName:"battlegauntlets",onlySetForClassId:true,props:[{prop:"ac",par:"",min:45,max:50},{prop:"dmg-cold",par:"150",min:6,max:18},{prop:"half-freeze",par:"",min:1,max:1},{prop:"gold%",par:"",min:56,max:56},{prop:"str",par:"",min:10,max:10},{prop:"dex",par:"",min:15,max:15}]},
  "mavinastenet": {name:"M'avina's Tenet",setName:"M'avina's Battle Hymn",key:"mavinastenet",setKey:"mavinasbattlehymn",code:"zvb",classId:391,classIdName:"sharkskinbelt",onlySetForClassId:true,props:[{prop:"ac",par:"",min:50,max:50},{prop:"move2",par:"",min:20,max:20},{prop:"manasteal",par:"",min:5,max:5},{prop:"light",par:"",min:5,max:5}]},
  "mavinascaster": {name:"M'avina's Caster",setName:"M'avina's Battle Hymn",key:"mavinascaster",setKey:"mavinasbattlehymn",code:"amc",classId:302,classIdName:"grandmatronbow",onlySetForClassId:true,props:[{prop:"dmg%",par:"",min:188,max:188},{prop:"swing3",par:"",min:40,max:40},{prop:"magicarrow",par:"",min:1,max:1},{prop:"att",par:"",min:50,max:50}]},
  "tellingofbeads": {name:"Telling of Beads",setName:"The Disciple",key:"tellingofbeads",setKey:"thedisciple",code:"amu",classId:520,classIdName:"amulet",onlySetForClassId:false,props:[{prop:"res-pois",par:"",min:35,max:50},{prop:"allskills",par:"",min:1,max:1},{prop:"res-cold",par:"",min:18,max:18},{prop:"thorns",par:"",min:8,max:10}]},
  "layingofhands": {name:"Laying of Hands",setName:"The Disciple",key:"layingofhands",setKey:"thedisciple",code:"ulg",classId:450,classIdName:"bramblemitts",onlySetForClassId:true,props:[{prop:"ac",par:"",min:25,max:25},{prop:"swing2",par:"",min:20,max:20},{prop:"res-fire",par:"",min:50,max:50},{prop:"dmg-demon",par:"",min:350,max:350},{prop:"hit-skill",par:"101",min:10,max:3}]},
  "riteofpassage": {name:"Rite of Passage",setName:"The Disciple",key:"riteofpassage",setKey:"thedisciple",code:"xlb",classId:385,classIdName:"demonhideboots",onlySetForClassId:true,props:[{prop:"ac",par:"",min:25,max:25},{prop:"move3",par:"",min:30,max:30},{prop:"half-freeze",par:"",min:1,max:1},{prop:"stam",par:"",min:15,max:25}]},
  "spiritualcustodian": {name:"Spiritual Custodian",setName:"The Disciple",key:"spiritualcustodian",setKey:"thedisciple",code:"uui",classId:429,classIdName:"duskshroud",onlySetForClassId:true,props:[{prop:"ac",par:"",min:305,max:415},{prop:"res-fire",par:"",min:24,max:24},{prop:"gethit-skill",par:"48",min:25,max:3},{prop:"dmg-pois",par:"50",min:125,max:175}]},
  "credendum": {name:"Credendum",setName:"The Disciple",key:"credendum",setKey:"thedisciple",code:"umc",classId:462,classIdName:"mithrilcoil",onlySetForClassId:true,props:[{prop:"ac",par:"",min:50,max:50},{prop:"str",par:"",min:10,max:10},{prop:"dex",par:"",min:10,max:10},{prop:"res-all",par:"",min:15,max:15}]},
  "dangoonsteaching": {name:"Dangoon's Teaching",setName:"Heaven's Brethren",key:"dangoonsteaching",setKey:"heavensbrethren",code:"7ma",classId:215,classIdName:"reinforcedmace",onlySetForClassId:true,props:[{prop:"dmg/lvl",par:"12",min:0,max:0},{prop:"swing3",par:"",min:40,max:40},{prop:"hit-skill",par:"44",min:10,max:3},{prop:"dmg-fire",par:"",min:20,max:30}]},
  "heavenstaebaek": {name:"Heaven's Taebaek",setName:"Heaven's Brethren",key:"heavenstaebaek",setKey:"heavensbrethren",code:"uts",classId:449,classIdName:"ward",onlySetForClassId:true,props:[{prop:"ac",par:"",min:50,max:50},{prop:"mana",par:"",min:100,max:100},{prop:"res-ltng",par:"",min:30,max:30},{prop:"thorns",par:"",min:30,max:30},{prop:"indestruct",par:"",min:1,max:1},{prop:"block",par:"",min:25,max:25},{prop:"block3",par:"",min:30,max:30}]},
  "haemosusadament": {name:"Haemosu's Adament",setName:"Heaven's Brethren",key:"haemosusadament",setKey:"heavensbrethren",code:"xrs",classId:366,classIdName:"cuirass",onlySetForClassId:true,props:[{prop:"ac",par:"",min:500,max:500},{prop:"ac-miss",par:"",min:35,max:35},{prop:"hp",par:"",min:75,max:75},{prop:"ac-hth",par:"",min:40,max:40},{prop:"ease",par:"",min:-20,max:-20}]},
  "ondalsalmighty": {name:"Ondal's Almighty",setName:"Heaven's Brethren",key:"ondalsalmighty",setKey:"heavensbrethren",code:"uhm",classId:426,classIdName:"spiredhelm",onlySetForClassId:true,props:[{prop:"ac",par:"",min:50,max:50},{prop:"ease",par:"",min:-40,max:-40},{prop:"hit-skill",par:"72",min:10,max:3},{prop:"str",par:"",min:10,max:10},{prop:"dex",par:"",min:15,max:15},{prop:"balance3",par:"",min:24,max:24}]},
  "guillaumesface": {name:"Guillaume's Face",setName:"Orphan's Call",key:"guillaumesface",setKey:"orphanscall",code:"xhm",classId:356,classIdName:"wingedhelm",onlySetForClassId:true,props:[{prop:"ac%",par:"",min:120,max:120},{prop:"balance3",par:"",min:30,max:30},{prop:"crush",par:"",min:35,max:35},{prop:"deadly",par:"",min:15,max:15},{prop:"str",par:"",min:15,max:15}]},
  "wilhelmspride": {name:"Wilhelm's Pride",setName:"Orphan's Call",key:"wilhelmspride",setKey:"orphanscall",code:"ztb",classId:393,classIdName:"battlebelt",onlySetForClassId:true,props:[{prop:"ac%",par:"",min:75,max:75},{prop:"manasteal",par:"",min:5,max:5},{prop:"res-cold",par:"",min:10,max:10},{prop:"lifesteal",par:"",min:5,max:5}]},
  "magnusskin": {name:"Magnus' Skin",setName:"Orphan's Call",key:"magnusskin",setKey:"orphanscall",code:"xvg",classId:381,classIdName:"sharkskingloves",onlySetForClassId:true,props:[{prop:"ac%",par:"",min:50,max:50},{prop:"res-fire",par:"",min:15,max:15},{prop:"swing2",par:"",min:20,max:20},{prop:"light",par:"",min:3,max:3},{prop:"att",par:"",min:100,max:100}]},
  "wihtstansguard": {name:"Wihtstan's Guard",setName:"Orphan's Call",key:"wihtstansguard",setKey:"orphanscall",code:"xml",classId:375,classIdName:"roundshield",onlySetForClassId:true,props:[{prop:"ac%",par:"",min:175,max:175},{prop:"block3",par:"",min:40,max:40},{prop:"block",par:"",min:55,max:55},{prop:"half-freeze",par:"",min:1,max:1},{prop:"light",par:"",min:5,max:5}]},
  "hwaninssplendor": {name:"Hwanin's Splendor",setName:"Hwanin's Majesty",key:"hwaninssplendor",setKey:"hwaninsmajesty",code:"xrn",classId:357,classIdName:"grandcrown",onlySetForClassId:true,props:[{prop:"regen",par:"",min:20,max:20},{prop:"red-mag",par:"",min:10,max:10},{prop:"res-cold",par:"",min:37,max:37},{prop:"ac%",par:"",min:100,max:100}]},
  "hwaninsrefuge": {name:"Hwanin's Refuge",setName:"Hwanin's Majesty",key:"hwaninsrefuge",setKey:"hwaninsmajesty",code:"xcl",classId:364,classIdName:"tigulatedmail",onlySetForClassId:true,props:[{prop:"ac",par:"",min:200,max:200},{prop:"res-pois",par:"",min:27,max:27},{prop:"hp",par:"",min:100,max:100},{prop:"gethit-skill",par:"42",min:10,max:3}]},
  "hwaninsseal": {name:"Hwanin's Seal",setName:"Hwanin's Majesty",key:"hwaninsseal",setKey:"hwaninsmajesty",code:"mbl",classId:346,classIdName:"belt",onlySetForClassId:false,props:[{prop:"dmg-ltng",par:"",min:3,max:33},{prop:"noheal",par:"",min:1,max:1},{prop:"ac/lvl",par:"12",min:0,max:0},{prop:"dmg-to-mana",par:"",min:12,max:12}]},
  "hwaninsjustice": {name:"Hwanin's Justice",setName:"Hwanin's Majesty",key:"hwaninsjustice",setKey:"hwaninsmajesty",code:"9vo",classId:151,classIdName:"bill",onlySetForClassId:true,props:[{prop:"att",par:"",min:330,max:330},{prop:"indestruct",par:"",min:1,max:1},{prop:"hit-skill",par:"45",min:10,max:3},{prop:"swing3",par:"",min:40,max:40},{prop:"dmg%",par:"",min:200,max:200},{prop:"dmg-ltng",par:"",min:5,max:25}]},
  "sazabiscobaltredeemer": {name:"Sazabi's Cobalt Redeemer",setName:"Sazabi's Grand Tribute",key:"sazabiscobaltredeemer",setKey:"sazabisgrandtribute",code:"7ls",classId:227,classIdName:"crypticsword",onlySetForClassId:true,props:[{prop:"dmg%",par:"",min:150,max:150},{prop:"dmg-cold",par:"50",min:25,max:35},{prop:"swing3",par:"",min:40,max:40},{prop:"dmg-demon",par:"",min:318,max:318},{prop:"indestruct",par:"",min:1,max:1},{prop:"dex",par:"",min:15,max:15},{prop:"str",par:"",min:5,max:5}]},
  "sazabisghostliberator": {name:"Sazabi's Ghost Liberator",setName:"Sazabi's Grand Tribute",key:"sazabisghostliberator",setKey:"sazabisgrandtribute",code:"upl",classId:437,classIdName:"balrogskin",onlySetForClassId:true,props:[{prop:"ac",par:"",min:400,max:400},{prop:"balance3",par:"",min:30,max:30},{prop:"str",par:"",min:25,max:25},{prop:"att-demon",par:"",min:300,max:300},{prop:"hp",par:"",min:50,max:75}]},
  "sazabismentalsheath": {name:"Sazabi's Mental Sheath",setName:"Sazabi's Grand Tribute",key:"sazabismentalsheath",setKey:"sazabisgrandtribute",code:"xhl",classId:355,classIdName:"basinet",onlySetForClassId:true,props:[{prop:"ac",par:"",min:100,max:100},{prop:"allskills",par:"",min:1,max:1},{prop:"res-fire",par:"",min:15,max:20},{prop:"res-ltng",par:"",min:15,max:20}]},
  "bulkathossacredcharge": {name:"Bul-Kathos' Sacred Charge",setName:"Bul-Kathos' Children",key:"bulkathossacredcharge",setKey:"bulkathoschildren",code:"7gd",classId:234,classIdName:"colossusblade",onlySetForClassId:true,props:[{prop:"crush",par:"",min:35,max:35},{prop:"res-all",par:"",min:20,max:20},{prop:"swing2",par:"",min:20,max:20},{prop:"knock",par:"",min:1,max:1},{prop:"dmg%",par:"",min:200,max:200}]},
  "bulkathostribalguardian": {name:"Bul-Kathos' Tribal Guardian",setName:"Bul-Kathos' Children",key:"bulkathostribalguardian",setKey:"bulkathoschildren",code:"7wd",classId:228,classIdName:"mythicalsword",onlySetForClassId:true,props:[{prop:"res-fire",par:"",min:50,max:50},{prop:"dmg-pois",par:"50",min:255,max:255},{prop:"swing2",par:"",min:20,max:20},{prop:"str",par:"",min:20,max:20},{prop:"dmg%",par:"",min:200,max:200}]},
  "cowkingshorns": {name:"Cow King's Horns",setName:"Cow King's Leathers",key:"cowkingshorns",setKey:"cowkingsleathers",code:"xap",classId:352,classIdName:"warhat",onlySetForClassId:true,props:[{prop:"ac",par:"",min:75,max:75},{prop:"half-freeze",par:"",min:1,max:1},{prop:"dmg-to-mana",par:"",min:35,max:35},{prop:"thorns",par:"",min:10,max:10}]},
  "cowkingshide": {name:"Cow King's Hide",setName:"Cow King's Leathers",key:"cowkingshide",setKey:"cowkingsleathers",code:"stu",classId:316,classIdName:"studdedleather",onlySetForClassId:true,props:[{prop:"res-all",par:"",min:18,max:18},{prop:"ac%",par:"",min:60,max:60},{prop:"hp",par:"",min:30,max:30},{prop:"gethit-skill",par:"53",min:18,max:5}]},
  "cowkingshoofs": {name:"Cow King's Hoofs",setName:"Cow King's Leathers",key:"cowkingshoofs",setKey:"cowkingsleathers",code:"vbt",classId:340,classIdName:"heavyboots",onlySetForClassId:false,props:[{prop:"ac",par:"",min:25,max:35},{prop:"move3",par:"",min:30,max:30},{prop:"mag%",par:"",min:25,max:25},{prop:"dex",par:"",min:20,max:20},{prop:"dmg-fire",par:"",min:25,max:35}]},
  "najspuzzler": {name:"Naj's Puzzler",setName:"Naj's Ancient Set",key:"najspuzzler",setKey:"najsancientset",code:"6cs",classId:261,classIdName:"elderstaff",onlySetForClassId:true,props:[{prop:"enr",par:"",min:35,max:35},{prop:"dmg%",par:"",min:150,max:150},{prop:"charged",par:"54",min:69,max:11},{prop:"cast3",par:"",min:30,max:30},{prop:"dmg-ltng",par:"",min:6,max:45},{prop:"mana",par:"",min:70,max:70},{prop:"allskills",par:"",min:1,max:1}]},
  "najslightplate": {name:"Naj's Light Plate",setName:"Naj's Ancient Set",key:"najslightplate",setKey:"najsancientset",code:"ult",classId:438,classIdName:"hellforgeplate",onlySetForClassId:true,props:[{prop:"ease",par:"",min:-60,max:-60},{prop:"hp",par:"",min:65,max:65},{prop:"res-all",par:"",min:25,max:25},{prop:"dmg-to-mana",par:"",min:45,max:45},{prop:"allskills",par:"",min:1,max:1},{prop:"ac",par:"",min:300,max:300}]},
  "najscirclet": {name:"Naj's Circlet",setName:"Naj's Ancient Set",key:"najscirclet",setKey:"najsancientset",code:"ci0",classId:418,classIdName:"circlet",onlySetForClassId:true,props:[{prop:"ac",par:"",min:75,max:75},{prop:"dmg-fire",par:"",min:25,max:35},{prop:"Light",par:"",min:5,max:5},{prop:"str",par:"",min:15,max:15},{prop:"gethit-skill",par:"53",min:12,max:5}]},
  "mcauleysparagon": {name:"McAuley's Paragon",setName:"McAuley's Folly",key:"mcauleysparagon",setKey:"mcauleysfolly",code:"cap",classId:306,classIdName:"cap",onlySetForClassId:false,props:[{prop:"mag%",par:"",min:35,max:35},{prop:"thorns",par:"",min:8,max:8},{prop:"ac/lvl",par:"8",min:0,max:0}]},
  "mcauleysriprap": {name:"McAuley's Riprap",setName:"McAuley's Folly",key:"mcauleysriprap",setKey:"mcauleysfolly",code:"vbt",classId:340,classIdName:"heavyboots",onlySetForClassId:false,props:[{prop:"move3",par:"",min:40,max:40},{prop:"att",par:"",min:100,max:100},{prop:"str",par:"",min:5,max:5},{prop:"dex",par:"",min:10,max:10}]},
  "mcauleystaboo": {name:"McAuley's Taboo",setName:"McAuley's Folly",key:"mcauleystaboo",setKey:"mcauleysfolly",code:"vgl",classId:335,classIdName:"heavygloves",onlySetForClassId:true,props:[{prop:"ac",par:"",min:20,max:25},{prop:"swing2",par:"",min:20,max:20},{prop:"hp",par:"",min:40,max:40},{prop:"dmg-pois",par:"75",min:30,max:36}]},
  "mcauleyssuperstition": {name:"McAuley's Superstition",setName:"McAuley's Folly",key:"mcauleyssuperstition",setKey:"mcauleysfolly",code:"bwn",classId:12,classIdName:"bonewand",onlySetForClassId:true,props:[{prop:"dmg%",par:"2",min:75,max:75},{prop:"mana",par:"",min:25,max:25},{prop:"manasteal",par:"",min:8,max:8},{prop:"cast3",par:"",min:20,max:20},{prop:"dmg-cold",par:"50",min:25,max:75}]},
};

/** Maps PascalCase name → lookup key (e.g. "TalRashasAdjudication" → "talrashasadjudication") */
export const setNameToKey: Record<string, string> = {
  "CiverbsWard": "civerbsward",
  "CiverbsIcon": "civerbsicon",
  "CiverbsCudgel": "civerbscudgel",
  "HsarusIronHeel": "hsarusironheel",
  "HsarusIronFist": "hsarusironfist",
  "HsarusIronStay": "hsarusironstay",
  "CleglawsTooth": "cleglawstooth",
  "CleglawsClaw": "cleglawsclaw",
  "CleglawsPincers": "cleglawspincers",
  "IrathasCollar": "irathascollar",
  "IrathasCuff": "irathascuff",
  "IrathasCoil": "irathascoil",
  "IrathasCord": "irathascord",
  "IsenhartsLightbrand": "isenhartslightbrand",
  "IsenhartsParry": "isenhartsparry",
  "IsenhartsCase": "isenhartscase",
  "IsenhartsHorns": "isenhartshorns",
  "VidalasBarb": "vidalasbarb",
  "VidalasFetlock": "vidalasfetlock",
  "VidalasAmbush": "vidalasambush",
  "VidalasSnare": "vidalassnare",
  "MilabregasOrb": "milabregasorb",
  "MilabregasRod": "milabregasrod",
  "MilabregasDiadem": "milabregasdiadem",
  "MilabregasRobe": "milabregasrobe",
  "CathansRule": "cathansrule",
  "CathansMesh": "cathansmesh",
  "CathansVisage": "cathansvisage",
  "CathansSigil": "cathanssigil",
  "CathansSeal": "cathansseal",
  "TancredsCrowbill": "tancredscrowbill",
  "TancredsSpine": "tancredsspine",
  "TancredsHobnails": "tancredshobnails",
  "TancredsWeird": "tancredsweird",
  "TancredsSkull": "tancredsskull",
  "SigonsGage": "sigonsgage",
  "SigonsVisor": "sigonsvisor",
  "SigonsShelter": "sigonsshelter",
  "SigonsSabot": "sigonssabot",
  "SigonsWrap": "sigonswrap",
  "SigonsGuard": "sigonsguard",
  "InfernalCranium": "infernalcranium",
  "InfernalTorch": "infernaltorch",
  "InfernalSign": "infernalsign",
  "BerserkersHeadgear": "berserkersheadgear",
  "BerserkersHauberk": "berserkershauberk",
  "BerserkersHatchet": "berserkershatchet",
  "DeathsHand": "deathshand",
  "DeathsGuard": "deathsguard",
  "DeathsTouch": "deathstouch",
  "AngelicSickle": "angelicsickle",
  "AngelicMantle": "angelicmantle",
  "AngelicHalo": "angelichalo",
  "AngelicWings": "angelicwings",
  "ArcticHorn": "arctichorn",
  "ArcticFurs": "arcticfurs",
  "ArcticBinding": "arcticbinding",
  "ArcticMitts": "arcticmitts",
  "ArcannasSign": "arcannassign",
  "ArcannasDeathwand": "arcannasdeathwand",
  "ArcannasHead": "arcannashead",
  "ArcannasFlesh": "arcannasflesh",
  "NatalyasTotem": "natalyastotem",
  "NatalyasMark": "natalyasmark",
  "NatalyasShadow": "natalyasshadow",
  "NatalyasSoul": "natalyassoul",
  "AldursStonyGaze": "aldursstonygaze",
  "AldursDeception": "aldursdeception",
  "AldursGauntlet": "aldursgauntlet",
  "AldursAdvance": "aldursadvance",
  "ImmortalKingsWill": "immortalkingswill",
  "ImmortalKingsSoulCage": "immortalkingssoulcage",
  "ImmortalKingsDetail": "immortalkingsdetail",
  "ImmortalKingsForge": "immortalkingsforge",
  "ImmortalKingsPillar": "immortalkingspillar",
  "ImmortalKingsStoneCrusher": "immortalkingsstonecrusher",
  "TalRashasFireSpunCloth": "talrashasfirespuncloth",
  "TalRashasAdjudication": "talrashasadjudication",
  "TalRashasLidlessEye": "talrashaslidlesseye",
  "TalRashasHowlingWind": "talrashashowlingwind",
  "TalRashasHoradricCrest": "talrashashoradriccrest",
  "GriswoldsValor": "griswoldsvalor",
  "GriswoldsHeart": "griswoldsheart",
  "GriswoldssRedemption": "griswoldssredemption",
  "GriswoldsHonor": "griswoldshonor",
  "TrangOulsGuise": "trangoulsguise",
  "TrangOulsScales": "trangoulsscales",
  "TrangOulsWing": "trangoulswing",
  "TrangOulsClaws": "trangoulsclaws",
  "TrangOulsGirth": "trangoulsgirth",
  "MavinasTrueSight": "mavinastruesight",
  "MavinasEmbrace": "mavinasembrace",
  "MavinasIcyClutch": "mavinasicyclutch",
  "MavinasTenet": "mavinastenet",
  "MavinasCaster": "mavinascaster",
  "TellingOfBeads": "tellingofbeads",
  "LayingOfHands": "layingofhands",
  "RiteOfPassage": "riteofpassage",
  "SpiritualCustodian": "spiritualcustodian",
  "Credendum": "credendum",
  "DangoonsTeaching": "dangoonsteaching",
  "HeavensTaebaek": "heavenstaebaek",
  "HaemosusAdament": "haemosusadament",
  "OndalsAlmighty": "ondalsalmighty",
  "GuillaumesFace": "guillaumesface",
  "WilhelmsPride": "wilhelmspride",
  "MagnusSkin": "magnusskin",
  "WihtstansGuard": "wihtstansguard",
  "HwaninsSplendor": "hwaninssplendor",
  "HwaninsRefuge": "hwaninsrefuge",
  "HwaninsSeal": "hwaninsseal",
  "HwaninsJustice": "hwaninsjustice",
  "SazabisCobaltRedeemer": "sazabiscobaltredeemer",
  "SazabisGhostLiberator": "sazabisghostliberator",
  "SazabisMentalSheath": "sazabismentalsheath",
  "BulKathosSacredCharge": "bulkathossacredcharge",
  "BulKathosTribalGuardian": "bulkathostribalguardian",
  "CowKingsHorns": "cowkingshorns",
  "CowKingsHide": "cowkingshide",
  "CowKingsHoofs": "cowkingshoofs",
  "NajsPuzzler": "najspuzzler",
  "NajsLightPlate": "najslightplate",
  "NajsCirclet": "najscirclet",
  "McAuleysParagon": "mcauleysparagon",
  "McAuleysRiprap": "mcauleysriprap",
  "McAuleysTaboo": "mcauleystaboo",
  "McAuleysSuperstition": "mcauleyssuperstition",
};

/** Maps lowercase PascalCase → lookup key for case-insensitive matching */
export const setNameToKeyLower: Record<string, string> = {
  "civerbsward": "civerbsward",
  "civerbsicon": "civerbsicon",
  "civerbscudgel": "civerbscudgel",
  "hsarusironheel": "hsarusironheel",
  "hsarusironfist": "hsarusironfist",
  "hsarusironstay": "hsarusironstay",
  "cleglawstooth": "cleglawstooth",
  "cleglawsclaw": "cleglawsclaw",
  "cleglawspincers": "cleglawspincers",
  "irathascollar": "irathascollar",
  "irathascuff": "irathascuff",
  "irathascoil": "irathascoil",
  "irathascord": "irathascord",
  "isenhartslightbrand": "isenhartslightbrand",
  "isenhartsparry": "isenhartsparry",
  "isenhartscase": "isenhartscase",
  "isenhartshorns": "isenhartshorns",
  "vidalasbarb": "vidalasbarb",
  "vidalasfetlock": "vidalasfetlock",
  "vidalasambush": "vidalasambush",
  "vidalassnare": "vidalassnare",
  "milabregasorb": "milabregasorb",
  "milabregasrod": "milabregasrod",
  "milabregasdiadem": "milabregasdiadem",
  "milabregasrobe": "milabregasrobe",
  "cathansrule": "cathansrule",
  "cathansmesh": "cathansmesh",
  "cathansvisage": "cathansvisage",
  "cathanssigil": "cathanssigil",
  "cathansseal": "cathansseal",
  "tancredscrowbill": "tancredscrowbill",
  "tancredsspine": "tancredsspine",
  "tancredshobnails": "tancredshobnails",
  "tancredsweird": "tancredsweird",
  "tancredsskull": "tancredsskull",
  "sigonsgage": "sigonsgage",
  "sigonsvisor": "sigonsvisor",
  "sigonsshelter": "sigonsshelter",
  "sigonssabot": "sigonssabot",
  "sigonswrap": "sigonswrap",
  "sigonsguard": "sigonsguard",
  "infernalcranium": "infernalcranium",
  "infernaltorch": "infernaltorch",
  "infernalsign": "infernalsign",
  "berserkersheadgear": "berserkersheadgear",
  "berserkershauberk": "berserkershauberk",
  "berserkershatchet": "berserkershatchet",
  "deathshand": "deathshand",
  "deathsguard": "deathsguard",
  "deathstouch": "deathstouch",
  "angelicsickle": "angelicsickle",
  "angelicmantle": "angelicmantle",
  "angelichalo": "angelichalo",
  "angelicwings": "angelicwings",
  "arctichorn": "arctichorn",
  "arcticfurs": "arcticfurs",
  "arcticbinding": "arcticbinding",
  "arcticmitts": "arcticmitts",
  "arcannassign": "arcannassign",
  "arcannasdeathwand": "arcannasdeathwand",
  "arcannashead": "arcannashead",
  "arcannasflesh": "arcannasflesh",
  "natalyastotem": "natalyastotem",
  "natalyasmark": "natalyasmark",
  "natalyasshadow": "natalyasshadow",
  "natalyassoul": "natalyassoul",
  "aldursstonygaze": "aldursstonygaze",
  "aldursdeception": "aldursdeception",
  "aldursgauntlet": "aldursgauntlet",
  "aldursadvance": "aldursadvance",
  "immortalkingswill": "immortalkingswill",
  "immortalkingssoulcage": "immortalkingssoulcage",
  "immortalkingsdetail": "immortalkingsdetail",
  "immortalkingsforge": "immortalkingsforge",
  "immortalkingspillar": "immortalkingspillar",
  "immortalkingsstonecrusher": "immortalkingsstonecrusher",
  "talrashasfirespuncloth": "talrashasfirespuncloth",
  "talrashasadjudication": "talrashasadjudication",
  "talrashaslidlesseye": "talrashaslidlesseye",
  "talrashashowlingwind": "talrashashowlingwind",
  "talrashashoradriccrest": "talrashashoradriccrest",
  "griswoldsvalor": "griswoldsvalor",
  "griswoldsheart": "griswoldsheart",
  "griswoldssredemption": "griswoldssredemption",
  "griswoldshonor": "griswoldshonor",
  "trangoulsguise": "trangoulsguise",
  "trangoulsscales": "trangoulsscales",
  "trangoulswing": "trangoulswing",
  "trangoulsclaws": "trangoulsclaws",
  "trangoulsgirth": "trangoulsgirth",
  "mavinastruesight": "mavinastruesight",
  "mavinasembrace": "mavinasembrace",
  "mavinasicyclutch": "mavinasicyclutch",
  "mavinastenet": "mavinastenet",
  "mavinascaster": "mavinascaster",
  "tellingofbeads": "tellingofbeads",
  "layingofhands": "layingofhands",
  "riteofpassage": "riteofpassage",
  "spiritualcustodian": "spiritualcustodian",
  "credendum": "credendum",
  "dangoonsteaching": "dangoonsteaching",
  "heavenstaebaek": "heavenstaebaek",
  "haemosusadament": "haemosusadament",
  "ondalsalmighty": "ondalsalmighty",
  "guillaumesface": "guillaumesface",
  "wilhelmspride": "wilhelmspride",
  "magnusskin": "magnusskin",
  "wihtstansguard": "wihtstansguard",
  "hwaninssplendor": "hwaninssplendor",
  "hwaninsrefuge": "hwaninsrefuge",
  "hwaninsseal": "hwaninsseal",
  "hwaninsjustice": "hwaninsjustice",
  "sazabiscobaltredeemer": "sazabiscobaltredeemer",
  "sazabisghostliberator": "sazabisghostliberator",
  "sazabismentalsheath": "sazabismentalsheath",
  "bulkathossacredcharge": "bulkathossacredcharge",
  "bulkathostribalguardian": "bulkathostribalguardian",
  "cowkingshorns": "cowkingshorns",
  "cowkingshide": "cowkingshide",
  "cowkingshoofs": "cowkingshoofs",
  "najspuzzler": "najspuzzler",
  "najslightplate": "najslightplate",
  "najscirclet": "najscirclet",
  "mcauleysparagon": "mcauleysparagon",
  "mcauleysriprap": "mcauleysriprap",
  "mcauleystaboo": "mcauleystaboo",
  "mcauleyssuperstition": "mcauleyssuperstition",
};

/** Maps full set name key → list of piece keys (e.g. "talrashaswrappings" → [...5 pieces]) */
export const setNameToItems: Record<string, string[]> = {
  "aldurswatchtower": ["aldursstonygaze","aldursdeception","aldursgauntlet","aldursadvance"],
  "angelicalraiment": ["angelicsickle","angelicmantle","angelichalo","angelicwings"],
  "arcannastricks": ["arcannassign","arcannasdeathwand","arcannashead","arcannasflesh"],
  "arcticgear": ["arctichorn","arcticfurs","arcticbinding","arcticmitts"],
  "berserkersgarb": ["berserkersheadgear","berserkershauberk","berserkershatchet"],
  "bulkathoschildren": ["bulkathossacredcharge","bulkathostribalguardian"],
  "cathanstraps": ["cathansrule","cathansmesh","cathansvisage","cathanssigil","cathansseal"],
  "civerbsvestments": ["civerbsward","civerbsicon","civerbscudgel"],
  "cleglawsbrace": ["cleglawstooth","cleglawsclaw","cleglawspincers"],
  "cowkingsleathers": ["cowkingshorns","cowkingshide","cowkingshoofs"],
  "deathsdisguise": ["deathshand","deathsguard","deathstouch"],
  "griswoldslegacy": ["griswoldsvalor","griswoldsheart","griswoldssredemption","griswoldshonor"],
  "heavensbrethren": ["dangoonsteaching","heavenstaebaek","haemosusadament","ondalsalmighty"],
  "hsarusdefense": ["hsarusironheel","hsarusironfist","hsarusironstay"],
  "hwaninsmajesty": ["hwaninssplendor","hwaninsrefuge","hwaninsseal","hwaninsjustice"],
  "immortalking": ["immortalkingswill","immortalkingssoulcage","immortalkingsdetail","immortalkingsforge","immortalkingspillar","immortalkingsstonecrusher"],
  "infernaltools": ["infernalcranium","infernaltorch","infernalsign"],
  "irathasfinery": ["irathascollar","irathascuff","irathascoil","irathascord"],
  "isenhartsarmory": ["isenhartslightbrand","isenhartsparry","isenhartscase","isenhartshorns"],
  "mavinasbattlehymn": ["mavinastruesight","mavinasembrace","mavinasicyclutch","mavinastenet","mavinascaster"],
  "mcauleysfolly": ["mcauleysparagon","mcauleysriprap","mcauleystaboo","mcauleyssuperstition"],
  "milabregasregalia": ["milabregasorb","milabregasrod","milabregasdiadem","milabregasrobe"],
  "najsancientset": ["najspuzzler","najslightplate","najscirclet"],
  "natalyasodium": ["natalyastotem","natalyasmark","natalyasshadow","natalyassoul"],
  "orphanscall": ["guillaumesface","wilhelmspride","magnusskin","wihtstansguard"],
  "sazabisgrandtribute": ["sazabiscobaltredeemer","sazabisghostliberator","sazabismentalsheath"],
  "sigonscompletesteel": ["sigonsgage","sigonsvisor","sigonsshelter","sigonssabot","sigonswrap","sigonsguard"],
  "talrashaswrappings": ["talrashasfirespuncloth","talrashasadjudication","talrashaslidlesseye","talrashashowlingwind","talrashashoradriccrest"],
  "tancredsbattlegear": ["tancredscrowbill","tancredsspine","tancredshobnails","tancredsweird","tancredsskull"],
  "thedisciple": ["tellingofbeads","layingofhands","riteofpassage","spiritualcustodian","credendum"],
  "trangoulsavatar": ["trangoulsguise","trangoulsscales","trangoulswing","trangoulsclaws","trangoulsgirth"],
  "vidalasrig": ["vidalasbarb","vidalasfetlock","vidalasambush","vidalassnare"],
};

/** Maps PascalCase set name → set key (e.g. "TalRashasWrappings" → "talrashaswrappings") */
export const setFullNameToKey: Record<string, string> = {
  "CiverbsVestments": "civerbsvestments",
  "HsarusDefense": "hsarusdefense",
  "CleglawsBrace": "cleglawsbrace",
  "IrathasFinery": "irathasfinery",
  "IsenhartsArmory": "isenhartsarmory",
  "VidalasRig": "vidalasrig",
  "MilabregasRegalia": "milabregasregalia",
  "CathansTraps": "cathanstraps",
  "TancredsBattlegear": "tancredsbattlegear",
  "SigonsCompleteSteel": "sigonscompletesteel",
  "InfernalTools": "infernaltools",
  "BerserkersGarb": "berserkersgarb",
  "DeathsDisguise": "deathsdisguise",
  "AngelicalRaiment": "angelicalraiment",
  "ArcticGear": "arcticgear",
  "ArcannasTricks": "arcannastricks",
  "NatalyasOdium": "natalyasodium",
  "AldursWatchtower": "aldurswatchtower",
  "ImmortalKing": "immortalking",
  "TalRashasWrappings": "talrashaswrappings",
  "GriswoldsLegacy": "griswoldslegacy",
  "TrangOulsAvatar": "trangoulsavatar",
  "MavinasBattleHymn": "mavinasbattlehymn",
  "TheDisciple": "thedisciple",
  "HeavensBrethren": "heavensbrethren",
  "OrphansCall": "orphanscall",
  "HwaninsMajesty": "hwaninsmajesty",
  "SazabisGrandTribute": "sazabisgrandtribute",
  "BulKathosChildren": "bulkathoschildren",
  "CowKingsLeathers": "cowkingsleathers",
  "NajsAncientSet": "najsancientset",
  "McAuleysFolly": "mcauleysfolly",
};

/** Maps lowercase set name → set key for case-insensitive matching */
export const setFullNameToKeyLower: Record<string, string> = {
  "civerbsvestments": "civerbsvestments",
  "hsarusdefense": "hsarusdefense",
  "cleglawsbrace": "cleglawsbrace",
  "irathasfinery": "irathasfinery",
  "isenhartsarmory": "isenhartsarmory",
  "vidalasrig": "vidalasrig",
  "milabregasregalia": "milabregasregalia",
  "cathanstraps": "cathanstraps",
  "tancredsbattlegear": "tancredsbattlegear",
  "sigonscompletesteel": "sigonscompletesteel",
  "infernaltools": "infernaltools",
  "berserkersgarb": "berserkersgarb",
  "deathsdisguise": "deathsdisguise",
  "angelicalraiment": "angelicalraiment",
  "arcticgear": "arcticgear",
  "arcannastricks": "arcannastricks",
  "natalyasodium": "natalyasodium",
  "aldurswatchtower": "aldurswatchtower",
  "immortalking": "immortalking",
  "talrashaswrappings": "talrashaswrappings",
  "griswoldslegacy": "griswoldslegacy",
  "trangoulsavatar": "trangoulsavatar",
  "mavinasbattlehymn": "mavinasbattlehymn",
  "thedisciple": "thedisciple",
  "heavensbrethren": "heavensbrethren",
  "orphanscall": "orphanscall",
  "hwaninsmajesty": "hwaninsmajesty",
  "sazabisgrandtribute": "sazabisgrandtribute",
  "bulkathoschildren": "bulkathoschildren",
  "cowkingsleathers": "cowkingsleathers",
  "najsancientset": "najsancientset",
  "mcauleysfolly": "mcauleysfolly",
};

/** Maps classId → list of set item keys sharing that classId */
export const setsByClassId: Record<number, string[]> = {
  2: ["berserkershatchet"],
  3: ["tancredscrowbill"],
  12: ["mcauleyssuperstition"],
  13: ["infernaltorch"],
  16: ["civerbscudgel"],
  17: ["milabregasrod"],
  27: ["angelicsickle"],
  30: ["isenhartslightbrand"],
  31: ["cleglawstooth"],
  32: ["deathstouch"],
  66: ["cathansrule"],
  67: ["arcannasdeathwand"],
  73: ["vidalasbarb"],
  74: ["arctichorn"],
  113: ["aldursgauntlet"],
  151: ["hwaninsjustice"],
  195: ["natalyasmark"],
  213: ["griswoldssredemption"],
  215: ["dangoonsteaching"],
  219: ["immortalkingsstonecrusher"],
  227: ["sazabiscobaltredeemer"],
  228: ["bulkathostribalguardian"],
  234: ["bulkathossacredcharge"],
  261: ["najspuzzler"],
  290: ["talrashaslidlesseye"],
  302: ["mavinascaster"],
  306: ["infernalcranium","mcauleysparagon"],
  307: ["arcannashead"],
  308: ["berserkersheadgear"],
  309: ["isenhartshorns"],
  310: ["sigonsvisor"],
  311: ["irathascoil","milabregasdiadem"],
  312: ["cathansvisage"],
  313: ["arcticfurs"],
  314: ["vidalasambush"],
  316: ["cowkingshide"],
  317: ["angelicmantle"],
  319: ["cathansmesh"],
  320: ["isenhartscase"],
  321: ["berserkershauberk"],
  324: ["sigonsshelter"],
  325: ["tancredsspine"],
  326: ["milabregasrobe"],
  327: ["arcannasflesh"],
  328: ["hsarusironfist"],
  329: ["cleglawsclaw"],
  330: ["civerbsward"],
  331: ["milabregasorb"],
  332: ["sigonsguard"],
  333: ["isenhartsparry"],
  334: ["deathshand"],
  335: ["mcauleystaboo"],
  336: ["cleglawspincers"],
  337: ["irathascuff","arcticmitts"],
  338: ["sigonsgage"],
  339: ["tancredshobnails"],
  340: ["cowkingshoofs","mcauleysriprap"],
  341: ["hsarusironheel"],
  342: ["vidalasfetlock"],
  343: ["sigonssabot"],
  344: ["deathsguard"],
  345: ["arcticbinding"],
  346: ["hsarusironstay","hwaninsseal"],
  347: ["irathascord","infernalsign"],
  348: ["sigonswrap"],
  349: ["tancredsskull"],
  352: ["cowkingshorns"],
  355: ["sazabismentalsheath"],
  356: ["guillaumesface"],
  357: ["hwaninssplendor"],
  358: ["talrashashoradriccrest"],
  364: ["hwaninsrefuge"],
  366: ["haemosusadament"],
  371: ["trangoulsscales"],
  372: ["griswoldsheart"],
  375: ["wihtstansguard"],
  381: ["magnusskin"],
  382: ["trangoulsclaws"],
  383: ["mavinasicyclutch"],
  384: ["immortalkingsforge"],
  385: ["riteofpassage"],
  387: ["natalyassoul"],
  388: ["aldursadvance"],
  389: ["immortalkingspillar"],
  391: ["mavinastenet"],
  392: ["talrashasfirespuncloth"],
  393: ["wilhelmspride"],
  394: ["immortalkingsdetail"],
  395: ["natalyastotem"],
  407: ["immortalkingswill"],
  418: ["najscirclet"],
  421: ["mavinastruesight"],
  426: ["ondalsalmighty"],
  427: ["griswoldsvalor"],
  429: ["spiritualcustodian"],
  434: ["natalyasshadow"],
  437: ["sazabisghostliberator"],
  438: ["najslightplate"],
  439: ["mavinasembrace"],
  440: ["talrashashowlingwind"],
  441: ["aldursdeception"],
  442: ["immortalkingssoulcage"],
  449: ["heavenstaebaek"],
  450: ["layingofhands"],
  462: ["credendum"],
  463: ["trangoulsgirth"],
  465: ["trangoulsguise"],
  470: ["aldursstonygaze"],
  486: ["trangoulswing"],
  502: ["griswoldshonor"],
  520: ["civerbsicon","irathascollar","vidalassnare","cathanssigil","tancredsweird","angelicwings","arcannassign","talrashasadjudication","tellingofbeads"],
  522: ["cathansseal","angelichalo"],
};
